### ISSUE TITLE
Abandoned Project ?

### ISSUE THREAD

**Issue by exmadesu** [hunternblz/bulk-cek-imei-kemenperin#1]
Mending di Archive repo nya bro, karena web **kemenperin** sekarang sudah di tutup aksesnya untuk public (butuh login) & hanya untuk instansi / perusahaan terkait.

Link = https://imei.kemenperin.go.id

![https://prnt.sc/9piVnY4OqgQR](https://img001.prntscr.com/file/img001/pw_vIX-LSiOvBrwK-jL8rQ.png)

**Comment by hunternblz** [comment]
ok
